S     = .
L     = .
C     = ../hmt_code
F77   = f77 
P     = -i4
CC    = cc
G     = 
#G     = -g

FLAGS = $G -fns -dalign -xdepend -fast -xO4 -xtarget=native -xarch=v8plusa -xchip=ultra -Dr8 -DBLAS -lm # -DV -DDEBUG

#FLAGS = $G -Dr8 -DBLAS -lm # -DV -DDEBUG -DMYMALLOC
#CDFLAGS  = -c -xO0 -g -DV -Dr8
#CFLAGS   = -c -O4 -DMYMALLOC -DV -Dr8
#CFLAGS   = -c -O4 -DV -Dr8
#CFLAGS   = -c -fast -xtarget=ultra -DV -Dr8
#FDFLAGS  = -c -O0 -g -Mr8
#FFLAGS   = -c -fast -xtarget=ultra 

NOBJS = prenek.o curve.o build.o build1.o build2.o bound.o plot.o xinterface.o glomod.o legend.o vprops.o iolib.o subs.o zipper2.o postnek6.o screen.o revert.o mxm.o xdriver.o error.o ivec.o queue.o stack.o bss_malloc.o adj_list.o pythag.o tqli.o smbwr.o sparse_matrix.o rsb_driver.o rsb.o


all: prex print


prex:	$(NOBJS)
	cc -o prex $(NOBJS) -L/usr/lib/X11 -lX11 -lfast -lm $(FLAGS) -xlic_lib=sunperf 


print:
	size prex


clean:
	'rm' *.o
	'rm' prex



#plot.o		: plot.f 	basics.inc	; $(F77) $P -c $(FLAGS) -O0 plot.f
#screen.o	: screen.f	basics.inc	; $(F77) $P -c $(FLAGS) -O0 screen.f
#mxm.o		: mxm.f		basics.inc	; $(F77) $P -c $(FLAGS) -O  mxm.f
#bound.o	: bound.f 	basics.inc	; $(F77) $P -c $(FLAGS) -O3 bound.f

plot.o		: plot.f 	basics.inc	; $(F77) $P -c $(FLAGS) plot.f
screen.o	: screen.f	basics.inc	; $(F77) $P -c $(FLAGS) screen.f
mxm.o		: mxm.f		basics.inc	; $(F77) $P -c $(FLAGS) mxm.f
bound.o		: bound.f 	basics.inc	; $(F77) $P -c $(FLAGS) bound.f

prenek.o	: prenek.f	basics.inc	; $(F77) $P -c $(FLAGS) prenek.f
zipper.o	: zipper.f	basics.inc	; $(F77) $P -c $(FLAGS) zipper.f
zipper2.o	: zipper2.f	basics.inc	; $(F77) $P -c $(FLAGS) zipper2.f
curve.o		: curve.f 	basics.inc	; $(F77) $P -c $(FLAGS) curve.f
build.o		: build.f 	basics.inc	; $(F77) $P -c $(FLAGS) build.f
xinterface.o	: xinterface.f 	basics.inc	; $(F77) $P -c $(FLAGS) xinterface.f
postnek6.o	: postnek6.f 	basics.inc	; $(F77) $P -c $(FLAGS) postnek6.f
glomod.o	: glomod.f 	basics.inc	; $(F77) $P -c $(FLAGS) glomod.f
legend.o	: legend.f	basics.inc	; $(F77) $P -c $(FLAGS) legend.f
vprops.o	: vprops.f	basics.inc	; $(F77) $P -c $(FLAGS) vprops.f
iolib.o		: iolib.f	basics.inc	; $(F77) $P -c $(FLAGS) iolib.f
subs.o		: subs.f	basics.inc	; $(F77) $P -c $(FLAGS) subs.f
build1.o	: build1.f	basics.inc	; $(F77) $P -c $(FLAGS) build1.f
build2.o	: build2.f	basics.inc	; $(F77) $P -c $(FLAGS) build2.f
g3d.o		: g3d.f		basics.inc	; $(F77) $P -c $(FLAGS) g3d.f
rsb.o		: rsb.F		basics.inc	; $(F77) $P -c $(FLAGS) rsb.F


xdriver.o	: xdriver.c		; cc -c $(FLAGS) xdriver.c
revert.o	: revert.c		; cc -c $(FLAGS) revert.c

bss_malloc.o	: $C/bss_malloc.c	; cc -c  $(FLAGS) $C/bss_malloc.c
error.o		: $C/error.c		; cc -c  $(FLAGS) $C/error.c
ivec.o		: $C/ivec.c		; cc -c  $(FLAGS) $C/ivec.c
queue.o		: $C/queue.c		; cc -c  $(FLAGS) $C/queue.c
stack.o		: $C/stack.c		; cc -c  $(FLAGS) $C/stack.c

pythag.o	: $L/pythag.c		; cc -c -I$C $(FLAGS) $L/pythag.c
tqli.o		: $L/tqli.c		; cc -c -I$C $(FLAGS) $L/tqli.c
smbwr.o		: $L/smbwr.c		; cc -c -I$C $(FLAGS) $L/smbwr.c
adj_list.o	: $L/adj_list.c		; cc -c -I$C $(FLAGS) $L/adj_list.c
rsb_driver.o	: $L/rsb_driver.c	; cc -c -I$C $(FLAGS) $L/rsb_driver.c
sparse_matrix.o	: $L/sparse_matrix.c	; cc -c -I$C $(FLAGS) $L/sparse_matrix.c


#rsb_ex.o	: $L/rsb_ex.c		; cc -c -I$C $(FLAGS) $L/rsb_ex.c
#sorts.o		: $L/sorts.c		; cc -c -I$C $(FLAGS) $L/sorts.c
