#!/bin/bash
set -e
if [ -f ./lib/libHYPRE.a ]; then
  exit 0
fi
if [ ! -f v2.11.2.tar.gz ]; then
  wget https://github.com/LLNL/hypre/archive/v2.11.2.tar.gz 
fi

tar -zxf *.tar.gz
cd hypre*/src
./configure --prefix=`pwd`/../.. --without-MPI
make -j4 install
