#! /bin/tcsh
#
#  Shell script that generated VisIt metafile blah.nek5000 either from SESSION.NAME or from the first command line argument
#

 set nfld = 0					# # of field files

 if ($#argv == 0) then
    if (-f SESSION.NAME) then
       set base = `head -1 SESSION.NAME`	# case name
    else
       set nfld = -1				# exit
       echo
       echo '  No SESSION.NAME file -- Use "visnek case_name"'
       echo
    endif
 else
       set base = $argv[1]
 endif


if ($nfld != -1) then

 echo
 echo '  Generating '$base'.nek5000 file ...'
 echo
 
#echo 'endian little'			>  $base.nek5000
#echo 'endian big'			>  $base.nek5000

 if  (-e		        $base.fld01) then
    set nfld = `ls -1	        $base{.fld[0-9][0-9]*}			| wc -l`
    echo 'filetemplate:	       '$base'.fld%02d'			>  $base.nek5000
 else if (-e 		   'A0/'$base'0.f00001') then
    set nfld = `ls -1	     A0/$base{0.f[0-9][0-9][0-9][0-9][0-9]}	| wc -l`
    echo 'filetemplate:	 A%01d/'$base'%01d.f%05d'		>  $base.nek5000
 else if (-e 		        $base'00.f00001') then
    set nfld = `ls -1	        $base{00.f[0-9][0-9][0-9][0-9][0-9]}	| wc -l`
    echo 'filetemplate:	       '$base'%02d.f%05d'		>  $base.nek5000
 else if (-e 		  'A00/'$base'00.f00001') then
    set nfld = `ls -1	    A00/$base{00.f[0-9][0-9][0-9][0-9][0-9]}	| wc -l`
    echo 'filetemplate:	 A%02d/'$base'%02d.f%05d'		>  $base.nek5000
 else if (-e 		        $base'000.f00001') then
    set nfld = `ls -1	        $base{000.f[0-9][0-9][0-9][0-9][0-9]}	| wc -l`
    echo 'filetemplate:	       '$base'%03d.f%05d'		>  $base.nek5000
 else if (-e 		 'A000/'$base'000.f00001') then
    set nfld = `ls -1	   A000/$base{000.f[0-9][0-9][0-9][0-9][0-9]}	| wc -l`
    echo 'filetemplate:	 A%03d/'$base'%03d.f%05d'		>  $base.nek5000
 else if (-e 		'A0000/'$base'0000.f00001') then
    set nfld = `ls -1	  A0000/$base{0000.f[0-9][0-9][0-9][0-9][0-9]}	| wc -l`
    echo 'filetemplate:	 A%04d/'$base'%04d.f%05d'		>  $base.nek5000
 else
    set nfld = `ls -1		$base{0.f[0-9][0-9][0-9][0-9][0-9]}	| wc -l`
    echo 'filetemplate:	       '$base'%01d.f%05d'		>  $base.nek5000
 endif
 endif
 endif


 echo 'firsttimestep: 1'	 	>> $base.nek5000
 echo 'numtimesteps: '$nfld		>> $base.nek5000

#echo 'meshcoords: 1'			>> $base.nek5000


 echo
 echo ' Assuming that coordinates are in the first file '$base'*.f*01 -- otherwise edit $base.nek5000 file ...'
 echo
 echo ' Also one may need to correct for an endian by inserting the first line "endian big" or "endian little" in case of, e.g., files transfered from other systems'
 echo
 echo
 echo ' Total '$nfld' file(s) are in the generated file '$base'.nek5000 ... Done!'
 echo

endif	# nfld != -1


