bdry.f:      COMMON /SCRUZ/ TMP1(LX1,LY1,LZ1,LELV)
bdry.f:      COMMON /SCRMG/ TMQ1(LX1,LY1,LZ1,LELV)
bdry.f:      COMMON /SCRSF/ TMP(LX1,LY1,LZ1,LELT)
bdry.f:      COMMON /SCREV / SII (LX1,LY1,LZ1,LELT)
bdry.f:      COMMON /SCRMG/ V1(LX1,LY1,LZ1,LELV)
bdry.f:      COMMON /SCRMG/ V1(LX1,LY1,LZ1,LELV)
coef.f:      COMMON /SCRNS/ XRM3 (LX3,LY3,LZ3,LELT)
coef.f:      COMMON /CTMP0/ ZSM3 (LX3,LY3,LZ3,LELT)
coef.f:      COMMON /CTMP1/ RXM3 (LX3,LY3,LZ3,LELT)
coef.f:      COMMON /SCRMG/ SYM3 (LX3,LY3,LZ3,LELT)
coef.f:      COMMON /SCREV/ TZM3 (LX3,LY3,LZ3,LELT)
coef.f:      COMMON /SCRNS/ XRM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /CTMP1/ ZSM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /SCRNS/ XRM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /CTMP1/ ZSM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /SCRNS/ XRM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /CTMP0/ WGTR1(LX1,LELT)
coef.f:      COMMON /SCRNS/ XRM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /SCRNS/ XRM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /CTMP1/ ZSM1(LX1,LY1,LZ1,LELT)
coef.f:      COMMON /CTMP0/ C  (LX1,LY1,LZ1,LELT)
comm_mpi_alpha.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi_alpha.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi_alpha.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi_alpha.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi_alpha.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi_alpha.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi_std.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi_std.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi_std.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi_std.f:      common /ctmp1/ istat(lx1*lelt)
comm_mpi_std.f:      common /scrns/ wrk(lx1*ly1*lz1*lelt)
comm_mpi_std.f:      common /ctmp1/ istat(lx1*lelt)
conduct.f:      COMMON /SCRNS/ TA(LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /SCRVH/ H1(LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /SCRUZ/ TA (LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /SCRUZ/ TA (LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /SCRNS/ TA (LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /SCRUZ/ TCH (LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /SCRNS/ VXN   (LX1,LY1,LZ1,LELV)
conduct.f:      COMMON /CTMP1/ RK1   (LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /SCRNS/ VXN   (LX1,LY1,LZ1,LELV)
conduct.f:      COMMON /CTMP1/ TMP1  (LX1,LY1,LZ1,LELT)
conduct.f:      COMMON /CTMP1/ WORK   (LXYZ1,LELT)
connect1.f:      COMMON /SCRUZ/ XM3 (LX3,LY3,LZ3,LELT)
connect1.f:      common /c_is1/ glo_num(1*lx1*ly1*lz1*lelv)
connect1.f:      common /scrns/ vertex (7*lx1*ly1*lz1*lelv)
connect2.f:      COMMON /SCRNS/ TA(LX1,LY1,LZ1,LELT),TB(LX1,LY1,LZ1,LELT)
connect2.f:      COMMON /CTMP0/ VO(LELT),XYZI(3,LELT),CG(3,LELT)
connect2.f:      COMMON /CTMP0/ XCG(LELT),YCG(LELT),ZCG(LELT)
convect.f:      common /scrns/ ct  (lxd*lyd*lzd*lelv*ldim)
convect.f:      common /scrvh/ bmsk(lx1*ly1*lz1*lelv)
convect.f:      common /scrmg/ r1  (lx1*ly1*lz1*lelv)
drive.f:      COMMON /SCRNS/ DUMMY2(LX1,LY1,LZ1,LELT,7)
drive.f:      COMMON /SCRUZ/ DUMMY3(LX1,LY1,LZ1,LELT,4)
drive.f:      COMMON /SCREV/ DUMMY4(LX1,LY1,LZ1,LELT,2)
drive.f:      COMMON /SCRVH/ DUMMY5(LX1,LY1,LZ1,LELT,2)
drive.f:      COMMON /SCRMG/ DUMMY6(LX1,LY1,LZ1,LELT,4)
drive.f:      COMMON /SCRCH/ DUMMY7(LX1,LY1,LZ1,LELT,2)
drive.f:      COMMON /SCRSF/ DUMMY8(LX1,LY1,LZ1,LELT,3)
drive.f:      COMMON /SCRCG/ DUMM10(LX1,LY1,LZ1,LELT,1)
drive.f:      COMMON /SCRUZ/ XM3 (LX3,LY3,LZ3,LELT)
drive.f:      COMMON /SCREV/ SII (LX1,LY1,LZ1,LELT)
drive.f:      COMMON /SCRUZ/ TA(LX1,LY1,LZ1,LELT)
drive.f:      common /SCRSF/ xm3(lx3,ly3,lz3,lelv)
drive.f:      common /cvflow_a/ vxc(kx1,ky1,kz1,lelv)
drive.f:      COMMON /SCRNS/ RESV1 (LX1,LY1,LZ1,LELV)
drive.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
drive.f:      COMMON /SCRNS/ rw1   (LX1,LY1,LZ1,LELV)
drive.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
drive.f:      COMMON /SCRHI/ H2INV (LX1,LY1,LZ1,LELV)
drive.f:      COMMON /SCRNS/ w(LX1,LY1,LZ1,LELT)
drive.f:      COMMON /SCRUZ/ v (LX1,LY1,LZ1,LELT)
drive.f:      COMMON /SCREV/ SII (LX1,LY1,LZ1,LELT)
drive.f:      COMMON /SCRUZ/ TA(LX1,LY1,LZ1,LELT)
eigsolv.f:      COMMON /SCRVH/ H1 (LX1,LY1,LZ1,LELT)
eigsolv.f:      COMMON /SCRHI/ H2INV (LX1,LY1,LZ1,LELV)
eigsolv.f:      COMMON /SCREV/  X1   (LX1,LY1,LZ1,LELT)
eigsolv.f:      COMMON /SCREV/  X1   (LX1,LY1,LZ1,LELT)
eigsolv.f:      COMMON /SCREV/ X2   (LX2,LY2,LZ2,LELV)
eigsolv.f:      COMMON /SCREV/ X2 (LX2,LY2,LZ2,LELV)
fast3d.f:      common /fastd/  sr(lxx,2,lelv),ss(lxx,2,lelv),st(lxx,2,lelv)
fast3d.f:      common /swaplengths/ l(lx1,ly1,lz1,lelv)
fasts.f:      common /scrpre/ v1(lx1,ly1,lz1,lelv)
fasts.f:      common /scrover/ ar(lelv)
fasts.f:      common /fastd/  sr(lxx,2,lelv),ss(lxx,2,lelv),st(lxx,2,lelv)
fasts.f:      common /swaplengths/ l(lx1,ly1,lz1,lelv)
fasts.f:      common /weightop/ w(lx2,lz2,2,3,lelv)
fasts.f:      common /weightop/ w(lx2,lz2,2,3,lelv)
genbox.f:      common /ctmp1/ indx(lelx+1)
genxyz.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
genxyz.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
gfdm_op.f:      common /fastdr/ lx(lelg),ly(lelg),lz(lelg)
gfdm_op.f:      common /fastdr/ lx(lelg),ly(lelg),lz(lelg)
hmholtz.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
hmholtz.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
hmholtz.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
hmholtz.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
hmholtz.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
hmholtz.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
hmholtz.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
hsmg.f:      common /scrns/ glo_num(1*lx1*ly1*lz1*lelv)
hsmg.f:      common /scrns/ glo_num(1*lx1*ly1*lz1*lelv)
hsmg.f:      common /quick/ ecrs  (lx2*ly2*lz2*lelv)  ! quick work array
hsmg.f:      common /scrhi/ h2inv (lx1,ly1,lz1,lelv)
hsmg.f:      common /scrvh/ h1    (lx1,ly1,lz1,lelv),
ic.f:      COMMON /CTMP1/ WORK(LX1,LY1,LZ1,LELV)
ic.f:c     COMMON /CBLELG/ CDUMP(LELG)
ic.f:      COMMON /scruz/ XM3 (LX1,LY1,LZ1,LELT)
ic.f:      common /scruz/ w2(4*lx1*ly1*lz1*lelv)
ic.f:      common /scruz/ w2(4*lx1*ly1*lz1*lelv)
ic.f:      common /scrcg/ pm1(lx1*ly1*lz1,lelv)
induct.f:      COMMON /SCRNS/  RESV1 (LX1,LY1,LZ1,LELV)
uuuu
induct.f:      COMMON /SCRVH/  H1    (LX1,LY1,LZ1,LELV)
induct.f:      COMMON /SCRNS/ TA1 (LX1,LY1,LZ1,LELV)
induct.f:      common /scrns/ ta1 (lx1,ly1,lz1,lelv)
induct.f:      COMMON /SCRNS/ TA1(LX1,LY1,LZ1,LELV)
induct.f:      common /scruz/ w1    (lx1,ly1,lz1,lelv)
induct.f:      common /scruz/ w1    (lx1,ly1,lz1,lelv)
induct.f:      common /scrns/ w1    (lx1,ly1,lz1,lelv)
induct.f:      common /scrvh/ h1    (lx1,ly1,lz1,lelv)
induct.f:      common /scrhi/ h2inv (lx1,ly1,lz1,lelv)
induct.f:      common /orthov/ pset(lx2*ly2*lz2*lelv*mxprev,nset)
induct.f:      COMMON /SCRNt/  bESV1 (LX1,LY1,LZ1,LELV)
induct.f:      COMMON /SCRNS/  RESV1 (LX1,LY1,LZ1,LELV)
induct.f:      COMMON /SCRVH/  H1    (LX1,LY1,LZ1,LELV)
induct.f:      common /dudxyj/ jacmi(lx1,ly1,lz1,lelt)
induct.f:      COMMON /SCRNS/ TA1 (LX1,LY1,LZ1,LELV)
induct.f:      common /scrns/ ta1 (lx1,ly1,lz1,lelv)
map2.f:      common /ctmp1/ map_st(lelg)
mvmesh.f:      COMMON /SCRUZ/ FM1(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRUZ/ FMT(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRSF/ PHR(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRSF/ PHR(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRSF/ WVX(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRCH/ WTX(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRMG/ WTZ(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRUZ/ DSA(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRVH/ H1(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRNS/ DW1  (LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRVH/ H1   (LX1,LY1,LZ1,LELT)
mvmesh.f:      common /scruz/ prt  (lx1,ly1,lz1,lelt)
mvmesh.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
mvmesh.f:      COMMON /SCRSF/ UX(LX1,LY1,LZ1,LELT)
mvmesh.f:      COMMON /SCRUZ/ XM3 (LX3,LY3,LZ3,LELT)
navier0.f:      common /scruz/ wk1(lx2*ly2*lz2*lelv)
navier0.f:      COMMON /SCRHI/  H2INV (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRHI/ H2INV (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ RESV1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/ TA1    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ VBDRY1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ TA1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCREV/ H1    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ TA1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/ TB1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ RESV1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ WORK  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/ TA1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCREV/ H1    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP0/ BP (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ TA1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
navier1.f:      common /fastmd/ ifdfrm(lelt), iffast(lelt), ifh2, ifsolv
navier1.f:      COMMON /SCRCH/ H1M2 (LX2,LY2,LZ2,LELV)
navier1.f:      COMMON /SCRNS/ MASK (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ TA   (LX2,LY2,LZ2,LELV)
navier1.f:      COMMON /CTMP0/ TA  (LX2,LY2,LZ2,LELV)
navier1.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
navier1.f:      COMMON /DUDXYJ/ JACMI(LX1,LY1,LZ1,LELT)
navier1.f:      COMMON /SCRCH/  CMASK1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP1/  MFI    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ TA1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/ TA1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/ TA1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ TA1(LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/ TA1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/ VEL1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ VXN   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP1/ RKX1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ RKY1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCREV/ RKZ1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRCH/ RKZ3  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ VXN   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP1/ TX1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRCH/ TZ1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP1/ WORK   (LXYZ1,LELT)
navier1.f:      COMMON /SCRNS/ TA1(LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ TA1(LX2,LY2,LZ2,LELV)
navier1.f:      COMMON /SCRNRM/ Y  (LX1,LY1,LZ1,LELT)
navier1.f:      COMMON /SCRMG/ Y1 (LX1,LY1,LZ1,LELT)
navier1.f:      COMMON /SCRCH/ TA2(LX1,LY1,LZ1,LELT)
navier1.f:      COMMON /SCRNS/ RESV1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ TB1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRUZ/   WP   (LX2,LY2,LZ2,LELV)
navier1.f:      COMMON /SCRCH/  CMASK1 (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP1/  MFI    (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP0/ TA1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRNS/ RES1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
navier1.f:      common /fastmd/ ifdfrm(lelt), iffast(lelt), ifh2, ifsolv
navier1.f:      common /dudxyj/ jacmi(lx1*ly1*lz1,lelt)
navier1.f:      COMMON /CTMP0/ TA1 (LX1,LY1,LZ1,LELV)
navier1.f:      common /fastmd/ ifdfrm(lelt), iffast(lelt), ifh2, ifsolv
navier1.f:      common /dudxyj/ jacmi(lx1*ly1*lz1,lelt)
navier1.f:      common /fastmd/ ifdfrm(lelt), iffast(lelt), ifh2, ifsolv
navier1.f:      common /dudxyj/ jacmi(lx1*ly1*lz1*lelt)
navier1.f:      COMMON /CTMP1/ WORK(LXYZ1,LELT)
navier1.f:      COMMON /SCRNS/ VXN   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /CTMP1/ RKX1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ RKY1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCREV/ RKZ1  (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRCH/ RKZ3  (LX1,LY1,LZ1,LELV)
navier1.f:      common /ctmp0/ work (lx2,ly2,lz2,lelv)
navier1.f:      COMMON /SCRNS/ TA1   (LX1,LY1,LZ1,LELV)
navier1.f:      COMMON /SCRMG/ W1    (LX1,LY1,LZ1,LELV)
navier2.f:      common /dudxyj/ jacmi(lx1*ly1*lz1,lelt)
navier2.f:      common /dudxyj/ jacmi(lx1*ly1*lz1,lelt)
navier3.f:      COMMON /SCRNS/ MASK (LX1,LY1,LZ1,LELV)
navier3.f:      common /scrprc/ uc(lx1*ly1*lz1*lelt)
navier4_div.f:      COMMON /SCRNS/ W1    (LX1,LY1,LZ1,LELV)
navier4_div.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
navier4_div.f:      COMMON /SCRCH/ PREXTR(LX2,LY2,LZ2,LELV)
navier4_div.f:      COMMON /SCRHI/ H2INV (LX1,LY1,LZ1,LELV)
navier4_div.f:      common /xyzu/ uic(lx1,ly1,lz1,lelv) , vic(lx1,ly1,lz1,lelv)
navier4_div.f:      COMMON /SCRUZ/  DIVV (LX2,LY2,LZ2,LELV)
navier4_div.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
navier4_div.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
navier4.f:      COMMON /SCRNS/ W1    (LX1,LY1,LZ1,LELV)
navier4.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
navier4.f:      COMMON /SCRCH/ PREXTR(LX2,LY2,LZ2,LELV)
navier4.f:      COMMON /SCRHI/ H2INV (LX1,LY1,LZ1,LELV)
navier4.f:      COMMON /SCRUZ/  DIVV (LX2,LY2,LZ2,LELV)
navier4.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
navier4.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
navier4_std.f:      COMMON /SCRNS/ W1    (LX1,LY1,LZ1,LELV)
navier4_std.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
navier4_std.f:      COMMON /SCRCH/ PREXTR(LX2,LY2,LZ2,LELV)
navier4_std.f:      COMMON /SCRHI/ H2INV (LX1,LY1,LZ1,LELV)
navier4_std.f:      COMMON /SCRUZ/  DIVV (LX2,LY2,LZ2,LELV)
navier4_std.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
navier4_std.f:      COMMON /CTMP0/ W1   (LX1,LY1,LZ1,LELT)
uuu
navier5.f:      common /scrns/         pm1(lx1,ly1,lz1,lelv)
navier5.f:      common /dudxyj/ jacmi(lx1*ly1*lz1,lelt)
navier5.f:      common /chkavg/  uavg(lx1,ly1,lz1,lelt)
navier5.f:      common /chkrms/  urms(lx1,ly1,lz1,lelt)
navier5.f:      common /ctmp0/ errg(10,lelg),wg(10*lelg)
navier5.f:      common /scrns/         sij (lx1*ly1*lz1*6*lelv)
navier5.f:      common /scrcg/         pm1 (lx1,ly1,lz1,lelv)
navier5.f:      common /scrsf/         xm0(lx1,ly1,lz1,lelt)
navier5.f:      common /dudxyj/ jacmi(lx1*ly1*lz1,lelt)
navier5.f:      common /scrns/ ur(lx1*ly1*lz1*lelv)
navier5.f:      common /scrns/ ur(lx1*ly1*lz1*lelv)
navier5_mom.f:      common /SCRNS/         pm1(lx1,ly1,lz1,lelv)
navier5_mom.f:      common /dudxyj/ jacmi(lx1*ly1*lz1,lelt)
navier5_mom.f:      common /chkavg/  uavg(lx1,ly1,lz1,lelt)
navier5_mom.f:      common /chkrms/  urms(lx1,ly1,lz1,lelt)
navier6.f:      common /scrcg/ ntri(lelt+1),nmask(lelt+1)
navier8.f:      common /scrpre/ uc(lcr*lelt)
navier8.f:      common /scrpr2/ uc_out(lcr*lelt)
navier8.f:c     common /cvtx/ vertex(8*lelgt)
navier8.f:      common /scrch/ iwork(2,lx1*ly1*lz1*lelv)
navier8.f:      common /scrns/ w(7*lx1*ly1*lz1*lelv)
navier8.f:      common /vptsol/ a(27*lx1*ly1*lz1*lelv)
navier8.f:      common /vptsol/ a(lx1*ly1*lz1*lelt*27)
navier8.f:      common /screc/ uc(lcr*lelt),w(2*lx2*ly2*lz2)
navier8.f:      common /screc/ uc(lcr*lelt),w(2*lxyz)
navier8.f:      common  /ctmp0/ iw(lx1*ly1*lz1*lelv)
navier8.f:      common /scrpre/ uc(lcr*lelt)
navier8.f:      common /scrpr2/ uc_out(lcr*lelt)
navier8.f:      common /screc/ w(lx1,lx1,2),v(lx1,2,ldim-1,lelt)
navier8.f:      common /screc/ w(2,2,lx1),v(2,ly1,lz1,lelt)
navier8.f:      common /ctmp0/ w(lx1,lx1,2),v(lx1,2,l2,lelt)
navier8.f:      common /ctmp0/ w(2,2,lx1),v(2,ly1,lz1,lelt)
particle.f:      common /scruz/ vxl(lx1*ly1*lz1*lelt,3)
particle.f:      common /scrmg/ bw (lx1*ly1*lz1*lelt,2),xo(3)
perturb.f:      COMMON /SCRNS/  RESV1 (LX1,LY1,LZ1,LELV)
perturb.f:      COMMON /SCRVH/  H1    (LX1,LY1,LZ1,LELV)
perturb.f:      COMMON /SCRNS/ TA1 (LX1*LY1*LZ1*LELV)
perturb.f:      common /scrns/ ta1 (lx1,ly1,lz1,lelv)
perturb.f:      COMMON /SCRNS/ TA1(LX1,LY1,LZ1,LELV)
perturb.f:      common /scruz/ w1    (lx1,ly1,lz1,lelv)
perturb.f:      COMMON /SCRNS/ TA(LX1,LY1,LZ1,LELT)
perturb.f:      COMMON /SCRVH/ H1(LX1,LY1,LZ1,LELT)
perturb.f:      common /scruz/ ta (lx1,ly1,lz1,lelt)
perturb.f:      COMMON /SCRUZ/ TA (LX1,LY1,LZ1,LELT)
perturb.f:      COMMON /SCRNS/ TA (LX1,LY1,LZ1,LELT)
perturb.f:      common /scrns/ w1    (lx1,ly1,lz1,lelv)
perturb.f:      common /scrvh/ h1    (lx1,ly1,lz1,lelv)
perturb.f:      common /scrhi/ h2inv (lx1,ly1,lz1,lelv)
perturb.f:      COMMON /SCRCH/ PREXTR(LX2,LY2,LZ2,LELV)
perturb.f:      COMMON /CTMP0/ DPR (LX2,LY2,LZ2,LELV)
planx.f:      COMMON /SCRNS/  RESV1 (LX1,LY1,LZ1,LELV)
planx.f:      COMMON /SCRVH/  H1    (LX1,LY1,LZ1,LELV)
planx.f:      COMMON /SCRUZ/ W1    (LX1,LY1,LZ1,LELV)
planx.f:      COMMON /CTMP0/ DPR (LX2,LY2,LZ2,LELV)
prepost.f:      common /scrcg/ pm1 (lx1,ly1,lz1,lelv)
prepost.f:      common /scruz/ vxax   (lx1,ly1,lelv)
prepost.f:      common /scrmg/ tax    (lx1,ly1,lelt,ldimt)
prepost.f:      common /scrcg/ pm1    (lx1,ly1,lz1,lelv)
prepost.f:      common /scrcg/ pm1 (lx1,ly1,lz1,lelv)
prepost.f:      common /scrcg/ pm1    (lx1,ly1,lz1,lelv)
prepost.f:      common /scrvh/ ts   (lx1,ly1,lz1,lelt)
prepost.f:      common /scrsf/ sfx  (lx1,ly1,lz1,lelt)
prepost.f:      common /scrvh/ h1 (lx1,ly1,lz1,lelv)
prepost.f:      common /scruz/ ta1(lx1,ly1,lz1,lelv)
prepost.f:      common /scrvh/ h1(lx1,ly1,lz1,lelt)
prepost.f:      common /scruz/ ta(lx1,ly1,lz1,lelt)
prepost.f:      common /scrcg/ pm1 (lx1,ly1,lz1,lelv)
prepost.f:      common /scrcg/ pm1 (lx1,ly1,lz1,lelv)  ! mapped pressure
ssolv.f:      COMMON /SCRSS2/ DV1 (LX1,LY1,LZ1,LELV)
ssolv.f:      COMMON /SCRUZ/  W1  (LX1,LY1,LZ1,LELV)
ssolv.f:      COMMON /SCRMG/  T1  (LX1,LY1,LZ1,LELV)
ssolv.f:      COMMON /SCRVH/  H1  (LX1,LY1,LZ1,LELV)
ssolv.f:      COMMON /SCRUZ/  DELTAT (LX1,LY1,LZ1,LELT)
ssolv.f:      COMMON /SCRVH/  H1     (LX1,LY1,LZ1,LELT)
ssolv.f:      COMMON /SCRMG/ DIVFLD (LX2,LY2,LZ2,LELV)
ssolv.f:      COMMON /SCRNS/ W1    (LX1,LY1,LZ1,LELV)
ssolv.f:      COMMON /SCRVH/ H1    (LX1,LY1,LZ1,LELV)
subs1.f:      COMMON /CTMP1/ U(LX1,LY1,LZ1,LELV)
subs1.f:      COMMON /CTMP0/ X(LX1,LY1,LZ1,LELV)
subs1.f:      COMMON /SCRNS/ XRM1 (LX1,LY1,LZ1,LELV)
subs1.f:      COMMON /SCRMG/ ZRM1 (LX1,LY1,LZ1,LELV)
subs1.f:      COMMON /CTMP1/ U    (LX1,LY1,LZ1,LELV)
subs1.f:      COMMON /CTMP0/ X    (LX1,LY1,LZ1,LELV)
subs1.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
subs1.f:      COMMON /CTMP0/ WA (LX1,LY1,LZ1,LELT)
subs1.f:      COMMON /SCREV/  DPC(LX1,LY1,LZ1,LELT)
subs1.f:      COMMON /SCRCH/  P2 (LX1,LY1,LZ1,LELT)
subs1.f:      COMMON /SCRMG/  PP1(LX1,LY1,LZ1,LELT)
subs1.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
subs1.f:      COMMON /FASTMD/ IFDFRM(LELT), IFFAST(LELT), IFH2, IFSOLV
subs1.f:      COMMON /CTMP0/ EXZ(LX1,LY1,LZ1,LELT)
subs1.f:      COMMON /CTMP1/ EXX(LX1,LY1,LZ1,LELT)
subs1.f:      COMMON /SCRSF/ UR(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /CTMP1/ TXX(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /CTMP0/ TXZ(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCRSF/ T11(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCRMG/ DUMMY6(LX1,LY1,LZ1,LELT,3)
subs2.f:      COMMON /CTMP1/ TXX(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /CTMP0/ TXZ(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCRMG/ DUMMY6(LX1,LY1,LZ1,LELT,3)
subs2.f:      COMMON /SCRSF/ FR(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCREV/ EI2(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /CTMP1/ EXX(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /CTMP0/ EXZ(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCRMG/ AE1(LX1,LY1,LZ1,LELV)
subs2.f:      COMMON /SCRUZ/ E1(LX1,LY1,LZ1,LELV)
subs2.f:      COMMON /SCRMG/ AE1(LX1,LY1,LZ1,LELV)
subs2.f:      COMMON /SCRUZ/ E1(LX1,LY1,LZ1,LELV)
subs2.f:      COMMON /SCRVH/ HVMASK(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCREV/ HFMASK(LX1,LZ1,6,LELT)
subs2.f:      COMMON /SCRVH/ HVMASK(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCREV/ HFMASK(LX1,LZ1,6,LELT)
subs2.f:      COMMON /SCRCG/  VNMAG(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /SCRSF/ A1MASK(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /CTMP0/ WA(LX1,LY1,LZ1,LELT)
subs2.f:      COMMON /CTMP1/ S1(LX1,LY1,LZ1,LELT)
turb.f:      COMMON /SCRVH/ TA(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /SCRCH/ TA(LX1,LY1,LZ1,LELV),TB(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /SCRCH/ TA(LX1,LY1,LZ1,LELV),TB(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /SCRCH/ TA(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /SCRUZ/ TA(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /CTMP0/ EXZ(LX1,LY1,LZ1,LELT)
turb.f:      COMMON /CTMP1/ EXX(LX1,LY1,LZ1,LELT)
turb.f:      COMMON /SCRMG/ TA(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /SCRMG/ VISKIN(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /SCRUZ/ V1(LX1,LY1,LZ1,LELV)
turb.f:      COMMON /SCRNS/ RHS(LX1,LY1,LZ1,LELV)
