#!/bin/bash
# Nek5000 build config file

# source path 
SOURCE_ROOT="$HOME/Nek5000" 
SOURCE_ROOT_CORE="$SOURCE_ROOT/core"
SOURCE_ROOT_JL="$SOURCE_ROOT/jl"
SOURCE_ROOT_CMT="$SOURCE_ROOT/core/cmt"

# Fortran compiler
F77="mpif77"

# C compiler
CC="mpicc"


# OPTIONAL SETTINGS
# -----------------

# enable MPI (default true)
#IFMPI="false"

# enable profiling (default false)
#IFPROFILING="true"

# enable CMT (default false)
#IFCMT="true"

# enable AMG coarse grid solver (default XXT)
#IFAMG="true"
#IFAMG_DUMP="true"

# pre-processor symbol list 
# (set PPLIST=? to get a list of available symbols)
#PPLIST="?" 

# generic compiler flags
#G="-g"

# optimization flags
#OPT_FLAGS_STD=""
#OPT_FLAGS_MAG=""

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# linking flags
#USR_LFLAGS="-L/usr/lib -lfoo"

# CVODE path
#CVODE_DIR=$HOME/cvode/lib
 
# MOAB/iMESH path
#MOAB_DIR="$HOME/moab"

# For linking to MOAB, the following might be needed:
# NOTE: compiler specific, use the appropriate one depending on your compiler
# GNU:
# USR_LFLAGS="-lmpi_cxx -lstdc++"
# Intel:
# USR_LFLAGS="-cxxlib"
# PGI:
# USR_LFLAGS="-pgcpplibs"
# USR_LFLAGS=" -lmpi_cxx -lstdc++"

# enable VisIt in situ
#  Note: you can override the lib and include paths. VISIT_LIB and VISIT_INC
#  If VISIT_STOP is set the simulation will stop after first step and wait
#  for VisIt to connect.
#IFVISIT=true
#VISIT_INSTALL="/path/to/visit/current/linux-x86_64/"
#VISIT_STOP=true

###############################################################################
# DONT'T TOUCH WHAT FOLLOWS !!!
###############################################################################
# assign version tag
mver=1
# overwrite source path with optional 2nd argument
if [ -d $2 ] && [ $# -eq 2 ]; then
  SOURCE_ROOT="$2"
  echo "change source code directory to: ", $SOURCE_ROOT
  SOURCE_ROOT_CORE="$SOURCE_ROOT/core"
  SOURCE_ROOT_JL="$SOURCE_ROOT/jl"
  SOURCE_ROOT_CMT="$SOURCE_ROOT/core/cmt"
fi
# do some checks and create makefile
source $SOURCE_ROOT_CORE/makenek.inc
# compile
make -j4 -f makefile 2>&1 | tee compiler.out
exit 0
