#!/bin/bash
#
# nek5000 build script
# (c) 2008,2009 UCHICAGO ARGONNE, LLC
#

# source path 
SOURCE_ROOT="$HOME/nek5_svn/trunk/nek"

# plug-in list
PLUGIN_LIST=""

# pre-processor symbol list
PPLIST="" # MPIIO BLAS_MXM BG_MXM K10_MXM

# Fortran compiler
F77="mpif77"

# C compiler
CC="mpicc"


# OPTIONAL SWITCHES WILL FOLLOW
# -----------------------------

# enable MPI (default true)
#IFMPI="false"

# compiler flags
#G="-g"

# optimization flags
#OPT_FLAGS_STD="-qarch=450 -qtune=450"
#OPT_FLAGS_MAG="-O5 -qarch=450d -qtune=450"

# enable timing (default true)
#IFTIMING="false"

# enable AMG coarse grid solver (default XXT)
#IFAMG="true"
#IFAMG_DUMP="true"

# enable coupled nek (default false)
#IFNEKNEK="true"
 
# enable MOAB/IMESH (default false)
#IFMOAB="true"
#MOAB_DIR="$HOME/moab"

# auxilliary files to compile
# NOTE: source files have to located in the same directory as makenek
#       a makefile_usr.inc has to be provided containing the build rules 
#USR="foo.o"

# linking flags
#USR_LFLAGS="-L/usr/lib -lfoo"


###############################################################################
# User Settings End
###############################################################################

if [ ! -d $SOURCE_ROOT ]; then
  echo "FATAL ERROR: Cannot find $SOURCE_ROOT"
  exit 1
fi

# do some checks and create makefile
source $SOURCE_ROOT/makenek.inc

# compile source using multiple threads
make -j8 -f makefile 2>&1 | tee compiler.out

# clean up
mkdir obj 2>/dev/null
\mv *.o ./obj 2>/dev/null

exit 0
