#!/bin/bash
set -e

VER=2.15.1

if [ -f ./lib/libHYPRE.a ]; then
  exit 0
fi

if [ ! -f ../../../3rd_party/hypre/v$VER.tar.gz ]; then
  wget -O ../../../3rd_party/hypre/v$VER.tar.gz https://github.com/LLNL/hypre/archive/v$VER.tar.gz
fi

tar -zxvf ../../../3rd_party/hypre/v$VER.tar.gz
cd hypre*/src
./configure --prefix=`pwd`/../.. --without-MPI
make -j4 install
