#!/bin/bash
set -e
if [ -f ./lib/libHYPRE.a ]; then
  exit 0
fi

if [ ! -f ../../../3rd_party/hypre/*.tar.gz ]; then
  wget -O v2.14.0.tar.gz https://github.com/LLNL/hypre/archive/v2.14.0.tar.gz
fi

tar -zxf ../../../3rd_party/hypre/*.tar.gz
cd hypre*/src
./configure --prefix=`pwd`/../.. --without-MPI
make -j4 install
