#!/bin/bash

# install path
bin_nek_tools="$HOME/bin"

# compilers
CC="pgcc"
F77="pgf77"





























##################################

if [ $# -eq 0 ]; then
   echo "Usage: maketools [clean|all|tool(s)]"
   exit 1
fi

which `echo $F77 | awk '{print $1}'` 1>/dev/null
if [ $? -ne 0 ]; then
  echo "FATAL ERROR: Cannot find $F77!"
  exit 1
fi

which `echo $CC | awk '{print $1}'` 1>/dev/null
if [ $? -ne 0 ]; then
  echo "FATAL ERROR: Cannot find $CC!"
  exit 1
fi

if [ ! -d $bin_nek_tools  ]; then
  echo "FATAL ERROR: install path $bin_nek_tools does not exist!"
  exit 1
fi


case $F77 in
  pgf*)        R8="-r8"
               ;;
  gfortran)    R8="-fdefault-real-8"
               ;;
  ifort)       R8="-r8"
               ;;
  pathf*)      R8="-r8"
               ;;
  *xlf*)       R8="-qrealsize=8"
               ;;
  ftn)         R8="-r8"
               ;;
  *)           exit 1
               echo "Error: Unkown compiler!"
               ;;
esac

# Check if the compiler adds an underscore to external functions
cat > test_underscore.f << _ACEOF
      subroutine underscore_test
        call byte_write
      end
_ACEOF

$F77 -c test_underscore.f 2>&1 >/dev/null 
nm test_underscore.o | grep byte_write_ 1>/dev/null
if [ $? -eq 0 ]; then 
  US="-DUNDERSCORE"
fi
\rm test_underscore.* 2>/dev/null

export F77
export CC
export bin_nek_tools
export US
export R8

LIST=`ls -Cd */ | sed 's:\/::g'`
MODULES=`echo $LIST`
export MODULES

if [ "$1" == "clean" ]; then
   make clean
else
   if [ "$1" != "all" ]; then
      LIST=`echo $* | sed 's:\/::g'`
      MODULES=$LIST
   fi
   export MODULES
   make 
fi

