name: CI (macOS)

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: macos-latest

    strategy:
      matrix:
        test_case: [ 
            "Tools",
            "Ethier::test_PnPn2_Parallel",
            "Ethier::test_PnPn_Parallel"
        ]
        include:
          - test_case: "Tools"
            mpi: no
      fail-fast: false

    name: "${{ matrix.test_case }}"

    env:
      TEST_CASE: ${{ matrix.test_case }}
      MPI: "${{ matrix.mpi == 'no' && '0' || '1' }}"
      FC: "${{ matrix.mpi == 'no' && 'gfortran' || 'mpif77' }}"
      CC: "${{ matrix.mpi == 'no' && 'gcc' || 'mpicc' }}"

    steps:
      - uses: actions/checkout@v4

      - name: brew dependencies
        shell: bash
        run: |
          brew install gcc mpich cmake pytest
          #python -m pip install --upgrade pip
          #python -m pip install pytest

          mkdir -p "$RUNNER_TEMP/bin"

          # create soft link of gfortran rather than gfortran-15
          GFORTRAN_BIN="$(find "$(brew --prefix gcc)/bin" -name 'gfortran-*' | sort -V | tail -n 1)"
          GCC_BIN="$(find "$(brew --prefix gcc)/bin" -name 'gcc-[0-9]*' ! -name 'gcc-ar-*' ! -name 'gcc-nm-*' ! -name 'gcc-ranlib-*' | sort -V | tail -n 1)"

          ln -sf "$GFORTRAN_BIN" "$RUNNER_TEMP/bin/gfortran"
          ln -sf "$GCC_BIN" "$RUNNER_TEMP/bin/gcc"

          echo "$RUNNER_TEMP/bin" >> "$GITHUB_PATH"

          echo $GCC_BIN
          echo $GFORTRAN_BIN

      - name: Check compilers
        shell: bash
        run: |
          set -x
          which gcc || true
          which gfortran || true
          which mpicc || true
          which mpif77 || true
          gcc --version || true
          gfortran --version || true
          mpicc --version || true
          mpif77 --version || true

          which cmake || true
          cmake --version || true

          which pytest
          pytest --version

      - name: test
        shell: bash
        run: |
          pytest -s -v short_tests/NekTests.py::$TEST_CASE
